name: Mirror to JuGit

on:
  push:
    branches: ['**']
    tags: ['**']
  delete:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full mirror
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Push mirror to JuGit
        env:
          GITLAB_TOKEN: ${{ secrets.JUGIT_TOKEN }}
          JUGIT_URL: ${{ secrets.JUGIT_REPO_URL }}
        run: |
          git remote add jugit "https://oauth2:${GITLAB_TOKEN}@${JUGIT_URL#https://}"
          git push jugit --mirror
